---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: atomic-desktop
# description will be included in the image's metadata
description: My custom image based on Bazzite for my desktop PC

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: testing # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    install:
      - corectrl
      - goverlay
      - neovim
      - podman-compose
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      # KDE specific stuff
      - plasma-firewall-firewalld
      # when bazzite removes konsole eventually
      - konsole
      # needed for building sysext
      - erofs-utils
    remove:
      #- firefox # default firefox removed in favor of flatpak
      #- firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - nano
      - nano-default-editor
      - vim-minimal
      - default-editor
      - vim-enhanced
      # KDE specific stuff
      - kcharselect
      # remove bazzite bloat
      - discover-overlay
      - ublue-update
      - tuned-profiles-cpu-partitioning
      - webapp-manager

  - type: script
    scripts:
      # replace vi/vim binaries with nvim
      - vim.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
